#!/usr/bin/env bash

set -e

SHELL='/bin/bash'
export SHELL

# take a look around
readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ARGS="$@"

# prepare dotbot
cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# execute everything

dotbot() {
    local config
    config="$1"

    "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    -c "$config" $ARGS
}

printf "\n"
echo "Remember #1: you will be asked for the root password because some packages need to be installed."
echo "Remember #2: install script must have HTTPS access to the world because of github packages."
printf "\n"

dotbot install_steps/apt.yml
dotbot install_steps/shell.yml

