[boot]
systemd=true
[user]
default = insane
[automount]
enabled = true
root = /
mountFsTab = false
#options = metadata,uid=1000,gid=1000,umask=22,fmask=0111
options=uid=1000,gid=1000,umask=0022
# add this to /etc/fstab to have userspace mounted with regular 0644/0755
C:\Users\username  /c/Users/username  drvfs  metadata,uid=1000,gid=1000,umask=0022,fmask=0111  0  0
[network]
generateResolvConf = true

