[[ -n ${ZSH_DEBUGRC+1} ]] && zmodload zsh/zprof

typeset -U path fpath                 # без дублей в PATH/fpath
path=($HOME/.local/bin $path)         # свои бинари важнее системных

DOTFILES=$HOME/dotfiles
DOTZSH=$DOTFILES/zsh

bindkey -e

for f in $HOME/.config/env.d/*(N); do source $f; done

fpath=($DOTZSH/func.d $fpath)
autoload -Uz $DOTZSH/func.d/*(N:t)

eval "$(oh-my-posh init zsh --config $DOTFILES/ohmyposh/base.yml)"

ZINIT_HOME=${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git
source $ZINIT_HOME/zinit.zsh

zinit light zsh-users/zsh-completions

autoload -Uz compinit
() { if (( $# )); then compinit; else compinit -C; fi } $HOME/.zcompdump(N.mh+24)
zinit cdreplay -q

# TODO: не помню, зачем это; если `source <Tab>` работает без него — удалить
unset '_comps[source]'

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu no
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

for f in $HOME/.config/compinit.d/*(N); do source $f; done
(( $+commands[uv] )) && eval "$(uv generate-shell-completion zsh)"

for f in $DOTZSH/rc.d/*(N); do source $f; done

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:7"
zstyle ':fzf-tab:*' use-fzf-default-opts yes

source <(fzf --zsh)               # Ctrl-R / Ctrl-T / Alt-C
bindkey '^I' expand-or-complete
zinit light Aloxaf/fzf-tab        # Tab -> fzf-tab
zinit light sunlei/zsh-ssh        # `ssh <Tab>` -> zsh-ssh, всё остальное -> fzf-tab

zstyle :omz:plugins:ssh-agent lazy yes
zinit snippet OMZP::ssh-agent

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=blue'
zinit light zsh-users/zsh-autosuggestions

zinit light zsh-users/zsh-syntax-highlighting

bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

# границы слов для Ctrl-←/→, Ctrl-W и т.п.
# word-style unspecified = в word-chars перечислены РАЗДЕЛИТЕЛИ, а не символы слова,
# поэтому держим их в zstyle, а не в глобальном $WORDCHARS (там смысл обратный)
autoload -Uz select-word-style
select-word-style normal
zstyle ':zle:*' word-style unspecified
zstyle ':zle:*' word-chars $' \t\n-.*?_[]/~=&;!#$%^(){}<>'

HISTFILE=~/.histfile
HISTSIZE=99999
SAVEHIST=99999
setopt extended_history
setopt share_history
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_find_no_dups

[[ -n ${ZSH_DEBUGRC+1} ]] && zprof
